### ISSUE TITLE
[enhancement] Enhancement Proposal for mapping decorator (become business framework)

### ISSUE THREAD

**Issue by sergey-babayan-v** [Tinche/cattrs#110]
* cattrs version: from 1.2.0
* Python version: 3.7 and newer
* Operating System: any

### Description

Hi everyone, i have been working with attrs+cattrs in a while and realized that it could be amazing to encapsulate business logic only with these two packages (to keep it simple and reliable), and after analyzing several projects (including some of mine) find out that there are several barriers, but the general one is the mapping fields from nested or complex objects to dict which could be converted by cattr.structure. 

Problem abstraction:
Let's suppose we work with SQLAlchemy and have denormalizated database schema (with some replica fields and duplication of entity fields), and we have different sql queries in order to get these data. In language of business logic all these fields it's fields of the same business entity, and they should be mapped to same entity, BUT it's not a trivial task because of potential difference between SQL (for example) and  our business code. In Databases or any foreign system it may be that after each executed expression u get new entity with totaly new schema but it's just composition of your fields related to different business object.
Why not just user SQLAlchemy mapping?: Because when u for example used repository pattern u wanted to encapsulate ur business logic from concrete orm interfaces. 
### Example
We have entities:
```python
@attr.s()
class OrderPosition(Entity):
    order: Order
    handling_unit: HandlingUnit
    ...

@attr.s()
class Schema(Entity):
    name: str
    holder: Holder
    ...

```

Then for example we have repository
```python
class WagonRepository:
     wagon_with_production = attr.make_class({
         "wagon": attr.ib(type=Wagon), # Wagon(Entity)
         "production": attr.ib(type=Warehouse) # Warehouse(Entity)
     }) # you can omit declaring dynamic attrs classes for association just using composition of objects in entity defenition

    @classmethod
    @convert(
          wagon_with_production, 
          wagon="ShipmentWagon", 
          production="ShipmentProduction",
          some_field_of_entity="orm_field_a.property_b",
          realtion=convert(....., many=True)
      )
    def shift_plan_packed_wagons(session: Session, shift_plan: ShiftPlan) -> List[wagon_with_production]:
        # a lot of different joins to tables
        # each row in query is complex object with access to ShipmentWagon and  ShipmentProduction
        # One day maybe u will change ur database to other such as mongodb without sqlaclhemy uasge, or just change ur database schema
        # Only place where u must  reflect ur changes in codebase is Repository and it's convertors
        return query.all()
```

### What I Did

I have created such decorator **convert** (will publish in pull request soon) BUT it's a little bit not optimal, underhood it uses cattr.structure .

What do u think about it?

**Comment by Tinche** [comment]
I don't really understand what you're suggesting here, it seems too abstract. Could you explain further?

**Comment by Tinche** [comment]
Going to close due to lack of clarity, feel free to reopen with more info in the future :)
