### ISSUE TITLE
Mypy error on unstructure

### ISSUE THREAD

**Issue by gleb-chipiga** [Tinche/cattrs#112]
* cattrs version: 1.1.2
* Python version: 3.8.6
* Operating System: Linux x86-64

### Description
Run mypy on first example from readme and get error.

### What I Did

```python
import cattr

cattr.unstructure(True)
```

```bash
$ mypy --strict example.py
example.py:3: error: Call to untyped function (unknown) in typed context
Found 1 error in 1 file (checked 1 source file)
```

**Comment by Tinche** [comment]
Just added type annotations to unstructure (but unfortunately, due to the nature of cattrs, they won't be very useful for type checking).

**Comment by gleb-chipiga** [comment]
At least mypy won't throw an error when using `unstructure`.
