### ISSUE TITLE
Literal structuring error

### ISSUE THREAD

**Issue by hlynurf** [Tinche/cattrs#122]
* cattrs version: 1.2.0
* Python version: 3.8.3
* Operating System: Ubuntu 20.04

### Description

Trying to structure a class with a field that has the type Literal and got an unexpected error.

### What I Did
Here is a minified version of the code in order to reproduce. This works if the annotation of the field is changed to `str`.
```python
from typing import Literal

import attr
import cattr


@attr.s
class Test:
	a: Literal['a'] = attr.ib()


unstructured = {
	'a': 'a',
}

cattr.structure(unstructured, Test)
```
the stacktrace produced
```
Traceback (most recent call last):
  File "test_convert.py", line 16, in <module>
    cattr.structure(unstructured, Test)
  File "python3.8/site-packages/cattr/converters.py", line 199, in structure
    return self._structure_func.dispatch(cl)(obj, cl)
  File "python3.8/site-packages/cattr/converters.py", line 336, in structure_attrs_fromdict
    dispatch(type_)(val, type_) if type_ is not None else val
  File "python3.8/site-packages/cattr/converters.py", line 271, in _structure_default
    fn = make_dict_structure_fn(cl, self)
  File "python3.8/site-packages/cattr/gen.py", line 107, in make_dict_structure_fn
    mapping = generate_mapping(cl, mapping)
  File "python3.8/site-packages/cattr/gen.py", line 84, in generate_mapping
    for p, t in zip(get_origin(cl).__parameters__, get_args(cl)):
AttributeError: '_SpecialForm' object has no attribute '__parameters__'
```

**Comment by Tinche** [comment]
Yeah, we don't support literals right now. It's on my radar to add though, they also present some interesting opportunities for handling unions.

**Comment by Tinche** [comment]
Fixed in 1.7!

**Comment by playpauseandstop** [comment]
Hi @Tinche!

Thanks for fixing initial issue in `1.7`. I can confirm, that initial error is not longer raised by `cattrs`.

However, if `Literal` contains [several of items](https://docs.python.org/3/library/typing.html#typing.Literal) like `QuestionType = Literal["input", "option"]`, `cattrs` may fail with,

```
Exception: Literal typing.Literal['input', 'option'] not equal to option
```

Code to reproduce,

```py
from typing import Literal

import attr
import cattr


QuestionType = Literal["input", "option"]


@attr.frozen()
class Question:
    question_type: QuestionType


cattr.structure(cattr.unstructure(Question(question_type="option")), Question)
```

And the full error itself,

```
Traceback (most recent call last):
  File "/Users/playpauseandstop/Projects/cattrs-122/./cattrs-122.py", line 15, in <module>
    cattr.structure(cattr.unstructure(Question(question_type="option")), Question)
  File "/Users/playpauseandstop/Projects/cattrs-122/lib/python3.9/site-packages/cattr/converters.py", line 223, in structure
    return self._structure_func.dispatch(cl)(obj, cl)
  File "", line 3, in structure_Question
  File "/Users/playpauseandstop/Projects/cattrs-122/lib/python3.9/site-packages/cattr/converters.py", line 319, in _structure_literal
    raise Exception(f"Literal {type} not equal to {val}")
Exception: Literal typing.Literal['input', 'option'] not equal to option
```

---

After digging into [converters.py](https://github.com/Tinche/cattrs/blob/b079967b4e68c728654044097c36a1999fb0f850/src/cattr/converters.py#L317-L320) I found, that `cattrs` checking that `val` equals to `type.__args__[0]`, but what if instead `cattrs` will perform `val not in type.__args__` check?

Please, let me know if you're OK with the proposed change, so I'll be happy to provide PR with the fix.

**Comment by Tinche** [comment]
Oh, good catch. I approve of the change, but also add a simple test too
