### ISSUE TITLE
Unstructuring a tuple of objects no longer works

### ISSUE THREAD

**Issue by gmacon** [Tinche/cattrs#125]
* cattrs version: 1.2.0
* Python version: 3.7.9
* Operating System: Linux

### Description

There are a few spots in the code where I unstructure a tuple of attrs objects in preparation for JSON-encoding them. This stopped working with 1.2.0.

### What I Did

Here's a minimal reproducer:

```python
#!/usr/bin/env python3

import attr
import cattr

@attr.define()
class Foo:
    foo: str

assert cattr.unstructure((Foo("foo"),)) == ({"foo": "foo"},)
```

I've bisected this to 53fd2ade2e052fb1f66a0e22edcee8a2974f1881. From looking at that commit quickly, I'm guessing that switching from `_subclass(Sequence)` to `is_sequence` is causing a tuple to no longer be considered a sequence.

**Comment by Tinche** [comment]
Oh interesting. Taking a look.

**Comment by Tinche** [comment]
Fix prepared here: https://github.com/Tinche/cattrs/pull/126, need to test it a little more

**Comment by gmacon** [comment]
Nice, thanks!

**Comment by Tinche** [comment]
Fix committed, will go out with the next release (1.3.0).
