### ISSUE TITLE
Collections.abc types do not work like typing types

### ISSUE THREAD

**Issue by ZeeD26** [Tinche/cattrs#128]
* cattrs version: 1.3.0
* Python version: Python 3.9.1
* Operating System: macOS 11.2.1

### Description

Python 3.9 deprecated `typing.<containers>` in favor of using `collections.abc.<containers>`. Using `collections.abc.` containers does not work as expected, though.

### What I Did

```python
from collections import abc
import typing

from attr import define

from cattr import GenConverter


@define
class A:
    a: int


@define
class B:
    b: typing.MutableSequence[A]


@define
class C:
    c: abc.MutableSequence[A]


converter = GenConverter()


if __name__ == "__main__":
    a = A(1)

    b = B([a])
    print(converter.unstructure(b))

    c = C([a])
    print(converter.unstructure(c))
```

The actual output is:
```
{'b': [{'a': 1}]}
{'c': [A(a=1)]}
```

What I expected:
```
{'b': [{'a': 1}]}
{'c': [{'a': 1}]}
```

**Comment by ZeeD26** [comment]
Also note that introducing a unstructured hook via
```python
converter.register_unstructure_hook(
    abc.MutableSequence,
    partial(converter.unstructure, unstructure_as=typing.MutableSequence),
)
```
does not lead to the desired result.

**Comment by Tinche** [comment]
If the typing alternatives are deprecated with is worth fixing quickly. Will look into it over the next couple of days.

**Comment by Tinche** [comment]
Should be fixed in https://github.com/Tinche/cattrs/commit/da63135b9cdadabc5f74b6089591f21b3bdc352a

**Comment by ZeeD26** [comment]
Works like a charm. Thank you! Let me apologize in advance, I am currently formulating a new issue 😅
