### ISSUE TITLE
[Question] structuring/convert JSON File with CamelCase to structured data 

### ISSUE THREAD

**Issue by nicolasmendoza** [Tinche/cattrs#136]
* cattrs version: 1.0.0
* Python version: 3.7
* Operating System: Windows

### Description

We want to structure a file that contains a string JSON into our attr Class, but this JSON uses CamelCase, and our class of course uses snakes following PEP8 guidelines. 

### What I Did

```
# example.json
{
    productID: 27272,
    originMessage: "mobile"
}

```

```
# models.py

import attr

@attr.s(auto_attribs=True)
class ExampleClass:
    product_id: int
    origin_mesagge: str
```

```
# test_example.py

import cattr
from models import ExampleClass


def_test_structure:
     with open("example.json") as file:
             structured = cattr.structure(json.load(file), ExampleClass)
```

Of course, this will cause a TypeError because converters.py:326 expects a product_id, origin_message, and not in camelcase. 

Is there any way to handle this using cattr? , 

would be nice to add a new method like "structure.structure_from_json("file.json")" with the camelcase conversion incorporated. 

Thanks

**Comment by wakemaster39** [comment]
I personally feel camelcase conversion should be out of scope and leave it to pre-processing the data file coming in as there will be infinite ways people will bring in data and you can't accommodate them all.

Here is the code I use to handle this situation for myself when I am working with GraphQL, needs a bit of love but mostly works.

```python
# From this response in Stackoverflow
# http://stackoverflow.com/a/1176023/1072990
def to_snake_case(name: str) -> str:
    s1 = re.sub("(.)([A-Z][a-z]+)", r"\1_\2", name)
    return re.sub("([a-z0-9])([A-Z])", r"\1_\2", s1).lower()
    
def snake_case_dict(d: T) -> T:
    if not isinstance(d, dict) and not isinstance(d, (list, tuple, frozenset)):
        return d
    if isinstance(d, (list, tuple, frozenset)):
        return cast(T, [snake_case_dict(x) for x in d])
    res = {}
    for k, v in d.items():
        if k.startswith("__"):
            continue
        res[to_snake_case(k)] = snake_case_dict(v)
    return cast(T, res)
```

**Comment by nicolasmendoza** [comment]
Hi @wakemaster39 !, yeah, I agree with you, and currently, I'm working on a similar approach. Thanks for sharing
