### ISSUE TITLE
Enum in attr class no longer does unstructure since 1.2.0

### ISSUE THREAD

**Issue by nepix32** [Tinche/cattrs#158]
* cattrs version: 1.1.2 and 1.2.0
* Python version: 3.7.7
* Operating System: Win
* attrs version 20.3.0

### Description

Can no longer use an Enum-derived class in an attr.s class since cattrs>=1.2.0

### What I Did

```python
import attr

from enum import Enum, unique

@unique
class MyEnum(Enum):
    x = "Null"
    y = "One"

from cattr import unstructure, structure

mc2 = MyEnum("One")
print(unstructure(mc2))

print(structure("One", MyEnum))

@attr.s
class MyClass:
    prop_a: MyEnum = attr.ib()

myclass_obj = MyClass(prop_a="One")
print(unstructure(myclass_obj))
```

Output with cattrs==1.1.2

```
One
MyEnum.y
{'prop_a': 'One'}
```

Output with cattrs==1.2.0

```
One
MyEnum.y
Traceback (most recent call last):
  File "005_minimal_str.py", line 27, in <module>
    print(unstructure(myclass_obj))
  File "C:\Users\Public\winpython_20210713\WPy32-3770\python-3.7.7\lib\site-packages\cattr\converters.py", line 135, in unstructure
    )(obj)
  File "C:\Users\Public\winpython_20210713\WPy32-3770\python-3.7.7\lib\site-packages\cattr\converters.py", line 210, in unstructure_attrs_asdict
    rv[name] = dispatch(a.type or v.__class__)(v)
  File "C:\Users\Public\winpython_20210713\WPy32-3770\python-3.7.7\lib\site-packages\cattr\converters.py", line 226, in _unstructure_enum
    return obj.value
AttributeError: 'str' object has no attribute 'value'
```

Thanks in advance

**Comment by Tinche** [comment]
Hello,

```
myclass_obj = MyClass(prop_a="One")
```
is actually wrong. You're assigning a value of type `str` to a field of type `MyEnum`, and they are incompatible (Mypy would confirm if). Do this instead:

```
myclass_obj = MyClass(prop_a=MyEnum("One"))
```

**Comment by nepix32** [comment]
Realized *just after your answer* that in ``cattrs==1.1.2`` the ``unstructure`` would "work" for my application because the outcome of the ``unstructure`` would be ``str`` anyway. And in the older version the ``unstructure`` would not complain. Fixed my code, thanks for the answer.

Ok to close.
