### ISSUE TITLE
Use attr.ib type information

### ISSUE THREAD

**Issue by moltob** [Tinche/cattrs#16]
As of the just released version 17.3.0 of the attrs library, attributes can use an additional keyword argument `type` or even use Python 3.6 type information (see http://www.attrs.org/en/stable/examples.html#types).

cattrs currently only looks at the explicitly given metadata attribute.

Would adding support for the new type information of attr make sense? Would you accept a PR for this?

**Comment by Tinche** [comment]
Hi,

yes, of course. We can get rid of cattr.typed now. I plan on doing this myself in the very near future, so no need for a PR :)

**Comment by moltob** [comment]
Thanks a lot. Please close the ticket or leave it open as a reminder and doc of an upcoming feature, whatever you prefer.

Looking forward to it! :+1:

**Comment by moltob** [comment]
I've seen you implemented this already on master. Do you plan to release a new PyPI package anytime soon? I'd like to clean up my code... :smile:

**Comment by Tinche** [comment]
Yeah as soon as I get some more time to deal with docs and spuriously failing tests. :)

**Comment by moltob** [comment]
I am looking forward to the packaged version before I release version 1 of my depending software. Do you need help in fixing tests or writing docs?

**Comment by moltob** [comment]
Thanks!
