### ISSUE TITLE
`pip install cattrs` didn't install requirements automatically

### ISSUE THREAD

**Issue by pktangyue** [Tinche/cattrs#17]
* cattrs version: 0.5.0
* Python version: 2.7.13
* Operating System: macOS

### Description

use `pip install cattrs` dit not install functools32, singledispatch, enum34, typing automatically.
while use `python setup.py install` with source code, it works.

**Comment by Tinche** [comment]
Hm. Managed to reproduce this. Looks like we need to tweak setup.py. Thanks for reporting!

**Comment by Tinche** [comment]
I've pushed out a fixed 0.6.0. Can you confirm the dependencies get installed now?

**Comment by pktangyue** [comment]
Fixed, Thanks!
