### ISSUE TITLE
How can I structure to an OrderedDict?

### ISSUE THREAD

**Issue by pombredanne** [Tinche/cattrs#27]
`cattr.structure(OrderedDict([(1, 2), (3, 4)]), Dict)` returns an unordered mapping. Is there a way to structure to an ordered mapping instead? (I am on Python 2.7 btw)

**Comment by Tinche** [comment]
Yeah, so the problem there is no OrderedDict[k, v] in typing.

Try this:

```
from collections import OrderedDict

import cattr

cattr.register_structure_hook(OrderedDict, lambda v, _: OrderedDict(v))

print(cattr.structure(OrderedDict([(1, 2), (3, 4)]), OrderedDict))
```

**Comment by pombredanne** [comment]
Simple and clean. Thanks! I am digging your excellent attr extension to replace schematics code in https://github.com/nexB/scancode-toolkit/blob/1f6538874688de65b7b70bd09f39a6402c074110/src/packagedcode/models.py#L275 FWIW.
