### ISSUE TITLE
'install_requires' must be a string or list of strings

### ISSUE THREAD

**Issue by FHellmann** [Tinche/cattrs#29]
* cattrs version: 0.6.0
* Python version: 3.4.2
* Operating System: linux

### Description

The library can not be installed due to a wrong format of the install_requires field. So the library is unable to install and use.

### What I Did

```
python3 setup.py install

...

Installed /usr/local/lib/python3.4/dist-packages/My_Smart_Home-0.1.0-py3.4.egg
Processing dependencies for My-Smart-Home==0.1.0
Searching for cattrs==0.6.0
Reading https://pypi.python.org/simple/cattrs/
Best match: cattrs 0.6.0
Downloading https://pypi.python.org/packages/ab/6c/e490455f33c9c36ca14bfc7385e72b1b504192eea36aa39ff693604f0790/cattrs-0.6.0.tar.gz#md5=d61409430787857cd970b0cba7a64965
Processing cattrs-0.6.0.tar.gz
Writing /tmp/easy_install-u0fnf4u5/cattrs-0.6.0/setup.cfg
Running cattrs-0.6.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-u0fnf4u5/cattrs-0.6.0/egg-dist-tmp-jw_e8t2c
error: Setup script exited with error in cattrs setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
```

**Comment by Tinche** [comment]
Hi,

I don't think there's a problem with our install_requires since it works for basically everyone else. You might want to try upgrading your setuptools. Also, Python 3.4 hasn't been supported for a few versions now, sorry :)

**Comment by jaredjstewart** [comment]
Do you have any specific recommendations on which versions of setuptools and Python are supported?  I see `Supported Python versions: 2.7, 3.5, 3.6, 3.7` on the main readme.md for this repo, but I get the same error as above when building with Python 3.6.
