### ISSUE TITLE
Minor note re: test suite

### ISSUE THREAD

**Issue by aldanor** [Tinche/cattrs#33]
As I'm building the conda package for cattrs (https://github.com/conda-forge/staged-recipes/pull/5651), I've noticed one thing about the tests: they use relative imports. This is highly discouraged, especially when using tools aimed at environment isolation (like tox or conda-build). The reason being that you're not testing the installed package (which is what the end-user will have in their environment), but rather the raw source tree.

The fix is quite simple: remove `__init__.py` from `tests/` and use absolute imports; tox will work just fine, and this will make it possible to test it via conda-build. If you want to be able to quickly run local dev tests outside of tox, you can always do `PYTHONPATH=. py.test tests/` so it should be fine as well.

Cheers :)

**Comment by Tinche** [comment]
The tests use relative imports only for things defined in the test package. Cattrs components are imported using absolute imports.

If tests is not a package, we can't share test logic. Fixtures aren't enough :)

**Comment by aldanor** [comment]
Hmm, there’s `conftest.py` with `pytest_namespace()`?

**Comment by aldanor** [comment]
I’ve double-checked, there’s only 5 symbols that are ever imported from ‘tests/__init__.py‘ making it a suitable fit for pytest_namespace() indeed; and in fact they would work as fixtures perfectly fine as well :)

**Comment by aldanor** [comment]
Note: although you import cattrs stuff using absolute imports, I think you’re still actually importing from the source tree (easily verifiable by checking module’s `__file__`) - because of `tests/__init__.py`.

**Comment by Tinche** [comment]
I have come to the conclusion you have a point about our test suite. But instead of making our test suite not a package, I've gone with introducing a ``src`` directory like described here: https://hynek.me/articles/testing-packaging/.

Thanks for the idea!

**Comment by aldanor** [comment]
Cheers :)

// Btw cattrs is now available in conda as well: https://github.com/conda-forge/cattrs-feedstock
