### ISSUE TITLE
feature request: support for Python 3.7 data classes

### ISSUE THREAD

**Issue by anthrotype** [Tinche/cattrs#43]
Would it be desirable/feasible to extend cattrs deserialization/serialization support to [Python 3.7 Data Classes](https://docs.python.org/3/library/dataclasses.html)?
Or is it out of scope?
Thanks for this great little library.

**Comment by petergaultney** [comment]
Is this still under consideration? I'd be up for looking into it and seeing if I couldn't make a PR.

**Comment by ClaireNeveu** [comment]
@Tinche If you're willing to have this functionality I'd be happy to make a PR for it. I have existing code for this that I think would be fairly easy to integrate upstream.

**Comment by Tinche** [comment]
Sure. I would start by mimicking what the GenConverter does to generate functions for attrs classes, just for dataclasses.

**Comment by asford** [comment]
@ClaireNeveu did you have a chance to look at your existing code and see if it'd be PR-able?
If you can find the time to open even a _super_ rough draft PR I'd be happy to help tidy it up for testing and merge.
We've just run into this issue and would love to continue using `cattrs` on some `dataclasses`-based classes.

**Comment by Tinche** [comment]
@asford I've put something together over at https://github.com/Tinche/cattrs/tree/tin/dataclasses. Want to try it out and see if it works for you?

**Comment by ClaireNeveu** [comment]
Ah, I did put something together but I've been pretty sick the past two weeks and haven't found time to PR it.

**Comment by asford** [comment]
Thanks for the awesome responses.

@ClaireNeveu I hope you can take all the time you need to center on yourself and feel better. For what it's worth, a co-human-you've-probably-never-met-on-the-internet is sending well wishes.

@Tinche looks great so far! I _suspected_ this was going to be pretty doable, but glad to see it's not a massive or disruptive change. The hypothesis-driven tests are a little outside my zone of expertise, so I opened a sub-PR with the basic cases I'm working with. It required a few, minor additional fixes to use the `_compat` interface that I haven't fully tested.

https://github.com/Tinche/cattrs/pull/134

**Comment by Tinche** [comment]
Good news, this feature is essentially done! I expect to release it tomorrow.

**Comment by Tinche** [comment]
Released as 1.4.0.
