### ISSUE TITLE
Is there interest/value in making cattrs work on python 2.7?

### ISSUE THREAD

**Issue by adetokunbo** [Tinche/cattrs#5]
* cattrs version: 0.2.0
* Python version: 2.7.13
* Operating System: MacOS Sierra 10.12.2

### Description

I wanted to try to use cattrs on python 2.7 for a personal project
I know that this is supposed to be a python3-specific project, but ...

### What I Did

... I made a few changes, and was able to create a [branch](https://github.com/adetokunbo/cattrs/tree/port-to-py27/cattr) that successful runs the current tests on python 2.7.  I.e

```
tox -e py27
```

works.

There's still work to do:

- the changes have broken python3.5, though that looks to be due to differences between what's available in the typing [backport on pypi](https://pypi.python.org/pypi/typing) and what's available in python3.5, rather than changes needed to make cattrs work on py2.7

I can work on fixing the issues and submit a PR, but I wanted to get early feedback before spending time on it.  E.g, it'd be worth knowing if cattrs should support python2.7 or not.

**Comment by Tinche** [comment]
Hm. I was gonna say no since I don't really feel like spending time supporting 2.7 myself, but since you already did the work, why not?

I'm actually genuinely surprised typing.py actually works on 2.7.

I'm in the middle of a refactor of some functionality since cattrs doesn't currently work on 3.6 (and it can't work on 3.6 until at least 3.6.1 without using a different typing.py, which I plan on bundling just for the affected versions). So when that's done I'd be glad to review a PR adding 2.7 support.

Thanks for your interest!

**Comment by adetokunbo** [comment]
Thank you! - I'll resync my branch once your refactor is complete and send you a PR then.

**Comment by glyph** [comment]
@adetokunbo - Thanks for doing this!

**Comment by Tinche** [comment]
Alright, I've released 0.3.0 and done some refactoring. Now would be a good time to send in a PR :)

(By now I mean in the next month)

**Comment by adetokunbo** [comment]
Done :)

PTAL

**Comment by kdebrab** [comment]
As this seems to be the package I'm searching for and as I'm (still) working in python 2.7, I installed the latest development version using:
```
pip install git+git://github.com/Tinche/cattrs@4123112
```
However, I get the following error:
```python
import cattr
Traceback (most recent call last):
[...]
  File "C:\Python27\lib\site-packages\cattr\__init__.py", line 2, in <module>
    from .converters import Converter
[...]
  File "C:\Python27\lib\site-packages\cattr\converters.py", line 2, in <module>
    from ._compat import lru_cache, singledispatch
[...]
  File "C:\Python27\lib\site-packages\cattr\_compat.py", line 11, in <module>
    from .vendor.typing import *  # noqa
[...]
ImportError: No module named vendor.typing
```
When inspecting the `\site-packages\cattr\` folder, there is indeed no subfolder `vendor`, let alone the module `vendor\typing.py`... Could it be that `setup.py` somehow forgets about the subfolder `vendor`?

**Comment by Tinche** [comment]
@kdebrab Should work now! Report back if it doesn't :)
