### ISSUE TITLE
Structuring Generics

### ISSUE THREAD

**Issue by wakemaster39** [Tinche/cattrs#52]
I realized I forgot to file an issue before submitting a PR, but this is to capture #51 .

The problem I have experienced is complex object with generic can be tedious to make work. Take the below code as an example, to use cattrs I need to register a hook for type `~T` which in this case would be assign it to `int`, or I could register a hook on `M`. 

```
T = TypeVar("T")

@attrs(auto_attrib=True)
class M(Generic[T]):
    prop: List[T]

data = {
  "prop": [1,2,3]
}

result = structure(data, M)
```

If a TypeVar with the name `T` is used anywhere else in my code it must be of type int or structuring is going to have issues.; This gets even worse when you have nested generics that share the same type var name. I typically just use T more my generic variable name, so I run into this problem often.

To address this, what I would like to see cattrs support is passing a `_GenericAlias` into the structure function and automatically handle the structuring if possible. The code above would stay the same except the last line which would become

```
result = structure(data, M[str])
```

Given this support, I no longer need to manually register `~T` or M and the existing structuring mechanisms could be utilized to handle the structuring. The mentioned PR is my first pass at implementing this feature, looking to see if this i something the library is willing support before I continue the work in polishing the code, documentation and tests.

**Comment by Tinche** [comment]
Hi,

this is very interesting but I'm a little sick at the moment so it might take me a while to take a look. Thanks!

**Comment by wakemaster39** [comment]
@Tinche have you had any time to take a look at this?

I have been playing around with it a bunch more and cleared out all of the issues that I have run into and can say it makes me love cattrs even more.

I have started to use it in some of my smaller systems to try and get some load against it and see if I have find any more problems. I can tell you being able to replace custom and nested deserializer with typing is about as good as it gets for me..

**Comment by wakemaster39** [comment]
This had made it into our production environment for over 6 months now and things have been pretty stable so far. Going to be merging in the last changes to support python3.8 in the next couple days. 

If this is something that is of interest, I will happily put in the work to merge #51. If not I can release my own forked library but would like to work towards getting this merged in here.

**Comment by ZeeD26** [comment]
I am currently running into the same issue and I am wondering how to tackle structuring and unstructuring of generics...

**Comment by wakemaster39** [comment]
I should have closed this off once the PR was merged. structuring generics just works now. 

https://github.com/Tinche/cattrs/blob/master/tests/test_generics.py

Here are some unit tests with it, I am going to close out my old ticket. I would open a new one if you are still having issues.
