### ISSUE TITLE
add py.typed for MyPy

### ISSUE THREAD

**Issue by petergaultney** [Tinche/cattrs#60]
* cattrs version: 1.0.0.rc0

### Description

If `cattrs` is going to start supporting MyPy type checking (meaning I don't need my own stubs anymore), I think the standard practice, following PEP 561, is to add an empty `py.typed` file to the top level of the package alongside `__init__.py`.  This lets MyPy know that this package is safe to type-check. 

Maybe 1.0.0 isn't fully there, in which case it probably isn't time for this. But just in case it had been overlooked...

**Comment by Tinche** [comment]
Thanks, this is definitely something I'd be interested in. Consider submitting a quick PR?

**Comment by petergaultney** [comment]
PR made! I would also be happy to spend some additional time working on the internal typing of cattrs, if you're interested. I use `cattrs` pretty heavily at my job and am invested in the success of the project. :)
