### ISSUE TITLE
typing.Union manual disambiguation function troubles

### ISSUE THREAD

**Issue by decentral1se** [Tinche/cattrs#63]
* cattrs version: 0.9.0
* Python version: 3.7
* Operating System: Debian

### Description

Have `cattrs` structure the following:

```python
import typing
import attr
from foobar import (TypeOne, TypeTwo)

@attr.s(auto_attribs=True)
class Container:
    types: typing.List[typing.Union[TypeOne, TypeTwo]]

@attr.s(auto_attribs=True)
class TypeOne:
    pass

@attr.s(auto_attribs=True)
class TypeTwo:
    pass
```

And then have:

```python
cattr.structure(cattr.unstructure(Container()))
```

I tried to simplify / adapt the example for this ticket ...

### What I Did

Tried to write a disambiguation function but did not have much luck.

* https://cattrs.readthedocs.io/en/latest/structuring.html#unions
* https://cattrs.readthedocs.io/en/latest/structuring.html#registering-custom-structuring-hooks

```
ValueError: <class 'Container'> has no usable unique attributes.
```

### Goal

If anyone can help me along here, I'd glady submit a documentation PR.

Thanks for this great library :rocket:

**Comment by Tinche** [comment]
Hi, do you still need help with this? I was busy elsewhere :(

**Comment by decentral1se** [comment]
Hey, thanks for following up and no worries. I ended up doing something else and I am not sure that this bug report was really an issue of cattrs. Feel free to re-open if you want to investigate but I thought I would close off since I am not chasing it anymore :+1:
