### ISSUE TITLE
Add support for Python 3.8

### ISSUE THREAD

**Issue by zeburek** [Tinche/cattrs#71]
### Description

There is no support for Python 3.8 right now, but it has been released today

**Comment by zeburek** [comment]
@Tinche you forgot to publish 0.9.1 to pypi, so we couldn't use it :(

**Comment by zeburek** [comment]
If comeone still waiting for this - I've published this version with fixes for tests and docs in https://pypi.org/project/cattrs-3.8/

**Comment by llchan** [comment]
I appreciate the unofficial release, but can we keep this issue open until a real release is cut?

**Comment by zeburek** [comment]
There is #72 - support is added, but not published
