### ISSUE TITLE
Add a new release to PyPI

### ISSUE THREAD

**Issue by chadrik** [Tinche/cattrs#74]
There are about a year's worth of updates that would be great to use without having to build our own wheel.  I know you're probably super busy but hopefully can you find the time to get a release out.  

thanks!

**Comment by anthrotype** [comment]
yes please! thanks :+1:

**Comment by zeburek** [comment]
If comeone still waiting for this - I've published this version with fixes for tests and docs in https://pypi.org/project/cattrs-3.8/

**Comment by anthrotype** [comment]
it's a pity that you had to fork it. I wonder if @Tinche would be interested in inviting collaborators to the repo if he doesn't have time to be the only maintainer of the project?

**Comment by JasonGilholme** [comment]
Can this be closed now?  I noticed a release on Jan 3.  Thanks guys!
