### ISSUE TITLE
What help is needed to release the project?

### ISSUE THREAD

**Issue by toumorokoshi** [Tinche/cattrs#8]
Hi there,

cattrs is really nice! Do you need help getting it released?

From my perspective, being able to do nested deserialization and serialization of attrs objects to primitives is really, really cool.

I've been looking for a really fast library to pair up with work an api generation library I've been working on:

http://aiohttp-transmute.readthedocs.io/

and attrs w/ validators is by far the fastest. If it's a small push to get it released, I'd be glad to help.

**Comment by Tinche** [comment]
Uh, I need to get some time, that's all :)

I have an interesting feature in the `feature/typed` branch, I need to write some property tests for it and then I'll release 0.4.0. This might be Sunday-ish.

Thanks for your interest :)

**Comment by toumorokoshi** [comment]
Thanks for releasing 0.4.0! looking forward to 0.5.0
