### ISSUE TITLE
0.9.1 never released to PyPI

### ISSUE THREAD

**Issue by dargueta** [Tinche/cattrs#83]
### Description

I see release 0.9.1 added support for Python 3.8, but it's not available in PyPI and there's no tag for it. I have a third-party library I'm dependent on that pins it as `cattrs~=0.9` so it'd install 0.9.1 if it were present.

Would it be possible to tag bb48897a7f389332d6111a239dcf3bf4a11b526f as 0.9.1 and release it on PyPI?

**Comment by Tinche** [comment]
Sorry for the long delay. Can you use 1.0 instead? If not I can release 0.9.1 for you.

**Comment by dargueta** [comment]
> Can you use 1.0 instead?

Unfortunately no, it's a dependency of a dependency that I have no control over.

**Comment by Tinche** [comment]
I've uploaded 1.0.0 as 0.9.1 for you on PyPI!

**Comment by dargueta** [comment]
Thanks so much!
