### ISSUE TITLE
Provide new kind of hooks with re-entrant Converter dispatch

### ISSUE THREAD

**Issue by petergaultney** [Tinche/cattrs#90]
* cattrs version: 1.0.0

### Description

I'd love to see `cattrs` take one step further in the name of extensibility and could make a PR to that effect. I use `cattrs` quite heavily, and I've made my own extensions that hook into parts of the `Converter` that are clearly not part of the stable API. 

The core issue for my use cases is that Converters are a stateful object with information about "how" to convert various sorts of things (e.g. datetimes), but the registered dispatch hooks (part of that state) have no access to the Converter itself. This is unfortunate, since all of the registered dispatch hooks together constitute a "conversion context". When a user calls `converter.structure`, a complex structure hook that, for instance, wishes to customize behavior for a whole "category" of types (e.g. `attrs`), can do so by registering a "func hook". However, as soon as it does so, it loses the ability to meaningfully "re-enter" the context of the cattrs converter dispatch.

You can see [here](https://github.com/xoeye/typecats/blob/master/typecats/cattrs_hooks.py#L19) what I've done here to work around this - I monkey-patch the function dispatch solely in order to provide my structure and unstructure hooks with access to all of the existing `Converter` context, by intercepting every pass through all function-dispatched hooks. This allows me to still take advantage of how nicely `cattrs` handles all the "core" recursive transforms (sets, tuples, sequences, frozensets, mappings, etc), while injecting my own code as necessary. Effectively this is a form of "adding to" the core dispatch functionality without duplicating it. This is of course not very efficient, since it means an entire extra function call for every non-single-dispatched type in the object tree.

The approach that cattrs takes to managing these recursive transforms is quite nice, and _nearly_ general-purpose, but it makes `attrs` a special case by automatically identifying them with a function hook and then calling its own internal "hook" that has stateful access to the converter and its internal dispatch. Would you be willing to accept a PR that would provide two new styles of hooks - both singledispatch and function-dispatched - that provide the Converter object (or even just the dispatch function) itself as a parameter to the hooks when called? I think this is all that remains to allow a fully range of boilerplate-free dynamic usage of the underlying power of `cattrs` for complex use cases beyond `attrs` itself. I would be happy to take a stab at making such a PR if there were some chance you'd accept it.

**Comment by Tinche** [comment]
Hi Peter,

thanks for your interest in cattrs!

I have also needed to call back into the converter often. The reason I try to avoid adding additional types of hooks or smarts to hooks (like recognizing parameter names and injecting values based on them, i.e. a poor man's dependency injection) is to keep the API surface simple since it's already kinda complex.

So first, let me share what I do and ask if this is acceptable to your use case. Basically I define the hook as a closure around the converter.

```
converter = Converter()

def my_hook(val, cl):
    # I have access to `converter` here.
    ...

converter.register_structure_hook(MyClass, my_hook)
```

If you want to decouple your hook implementation from a particular converter, you can always create a factory function taking a converter:

```
def inject_my_hook(converter: Converter):
    def my_hook(val, cl):
        # I have access to `converter` here.
        ...

    converter.register_structure_hook(MyClass, my_hook)
```

I like the fact it keeps the API surface simple and uses Python built-in functionality instead.

Let me know what you think.

**Comment by petergaultney** [comment]
This is a good point, and it's exactly the sort of thing my patching approach 'effectively' does. In my case I particularly wanted to change specific `cattrs` behavior around `attrs` classes - by having access to the Converter context I could allow `cattrs` to 'select' the attrs unstructure hook, while I then used the actual `__attrs_attrs__` present to remove all keys with default values after unstructuring the attrs object. 

Thinking it over a bit more, there's really no particular reason not to take your simpler approach consistently.

Thanks for your time (and for an excellent library)!

I may have a separate 'request' that's more of a question, but I'll open something else for it.
