### ISSUE TITLE
Supported python verisons

### ISSUE THREAD

**Issue by tiptop96** [Tinche/cattrs#95]
I am wanting to use cattrs with python 3.6 and have ran some tests and so far there are no issues but I am confused about what versions are actually supported.

The badge says:
------------------
<img width="741" alt="bild" src="https://user-images.githubusercontent.com/31468763/94266653-bcdce280-ff3a-11ea-9285-95a04e5b7498.png">

While the read me says:
------------------
<img width="500" alt="bild" src="https://user-images.githubusercontent.com/31468763/94266708-d0884900-ff3a-11ea-8418-9cbdf37e82cc.png">

Which is correct and should I be worried about using 3.6?

**Comment by Tinche** [comment]
I'm preparing a new release supporting 3.9, so the README is for that :)

Feel free to stick with the current version which will continue working on 3.6 of course.

(I should add a note to the README explaining this.)
